jobs:
  include:
  - stage: Deploy Server
    if: &release_tag tag =~ /^\d+.\d+.\d+$/
    language: python
    python: 3.6
    before_script: cd server
    install:
    - pip3 install twine
    script:
    - echo TRAVIS_BRANCH=${TRAVIS_BRANCH}
    - echo TRAVIS_TAG=${TRAVIS_TAG}
    - python3 setup.py sdist bdist_wheel
    - twine upload --skip-existing dist/*

  - stage: Deploy VSCode Client
    if: *release_tag
    language: node_js
    node_js: node
    before_script: cd client/vscode
    install:
    - npm i -g vsce
    script:
    - npm version ${TRAVIS_TAG}
    - vsce publish publish -p ${VSCE_TOKEN}
