stages:
- name: deploy-server
  if: &release_tag branch = master
- name: deploy-vscode-client
  if: *release_tag

jobs:
  include:
  - stage: deploy-server
    language: python
    python: 3.6
    before_script: cd server
    install:
    - pip3 install twine
    script:
    - python3 setup.py sdist bdist_wheel
    - twine upload --skip-existing dist/*

  - stage: deploy-vscode-client
    language: node_js
    node_js: node
    before_script: cd client/vscode
    install:
    - npm i -g vsce
    script:
    - npm version ${TRAVIS_TAG}
    - vsce publish publish -p ${VSCE_TOKEN}
