jobs:
  include:
  - stage: Deploy Server
    if: &release_tag branch = master AND tag IS present
    language: python
    python: 3.6
    script:
    - python3 setup.py sdist bdist_wheel
    - twine upload --skip-existing dist/*

  - stage: Deploy VSCode Client
    if: *release_tag
    language: node_js
    node_js: node
    install:
    - npm i -g vsce
    script:
    - npm version ${TRAVIS_TAG}
    - vsce publish publish -p ${VSCE_TOKEN}
