jobs:
  include:
  - stage: Deploy Server
    if: &release_tag tag =~ /^\d+\.\d+\.\d+$/
    dist: bionic
    language: python
    python: 3.7
    before_install:
    - cd server
    script:
    - python3 setup.py sdist bdist_wheel
    - twine upload --skip-existing dist/*

  - stage: Deploy Clients
    name: VSCode
    if: *release_tag
    language: node_js
    node_js: node
    before_install:
    - cd client/vscode
    script:
    - npm version ${TRAVIS_TAG}
    - vsce publish -p ${VSCE_TOKEN}

  - stage: Deploy Clients
    name: IntelliJ
    if: *release_tag
    language: java
    jdk: openjdk8
    before_install:
    - cd client/intellij
    script:
    - ./gradlew publishPlugin -Ptoken=${INTELLIJ_TOKEN}
