jobs:
  include:
  - stage: Deploy Server
    if: (branch = master) AND (tag =~ /^\d+.\d+.\d+$/)
    language: python
    python: 3.6
    script:
    - python3 setup.py sdist bdist_wheel
    - twine upload --skip-existing dist/*

  - stage: Deploy VSCode Client
    if: (branch = master) AND (tag =~ /^\d+.\d+.\d+$/)
    language: node_js
    node_js: node
    install:
    - npm i -g vsce
    script:
    - npm version ${TRAVIS_TAG}
    - vsce publish publish -p ${VSCE_TOKEN}
