version: 2.1

always_run: &always_run
  filters:
    tags:
      only: /.*/

release_only: &release_only
  filters:
    tags:
      only: /^\d+.\d+.\d+$/
    branches:
      ignore: /.*/

workflows:
  deploy:
    jobs:
    - deploy_server:
        <<: *release_only

jobs:
  deploy_server:
    docker:
    - image: circleci/python
    steps:
    - checkout
    - run:
        command: |
          echo -e "[pypi]" >> ~/.pypirc
          echo -e "username = ${PYPI_USERNAME}" >> ~/.pypirc
          echo -e "password = ${PYPI_PASSWORD}" >> ~/.pypirc
    - run:
        workspace_directory: server
        command: |
          set -e

          python3 setup.py sdist bdist_wheel

          pip3 install --user twine
          python3 -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*
