version: 2.1

all_tags: &all_tags
  filters:
    tags:
      only: /.*/

release_only: &release_only
  filters:
    tags:
      only: /^\d+.\d+.\d+$/
    branches:
      ignore: /.*/

workflows:
  deploy:
    jobs:
    - deploy_server:
        <<: *release_only

server_defaults: &server_defaults
  docker:
  - image: circleci/python

jobs:
  deploy_server:
    <<: *server_defaults
    steps:
    - run:
        working_directory: server
        command: |
          set -e

          python3 setup.py sdist bdist_wheel

          pip3 install --user twine
          python3 -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*
