version: 2.1

always_run: &always_run
  filters:
    tags:
      only: /.*/

release_only: &release_only
  filters:
    tags:
      only: /^\d+.\d+.\d+$/
    branches:
      ignore: /.*/

workflows:
  deploy:
    jobs:
    - test_secret
    - deploy_server:
        <<: *release_only
    - deploy_client_vscode:
        <<: *release_only
        requires:
        - deploy_server

jobs:
  test_secret:
    docker:
    - image: circleci/python
    steps:
    - run:
        command: |
          echo ${TEST_SECRET}

  deploy_server:
    docker:
    - image: circleci/python
    steps:
    - checkout
    - run:
        working_directory: server
        command: |
          set -e

          python3 setup.py sdist bdist_wheel

          pip3 install --user twine
          python3 -m twine upload dist/*

  deploy_client_vscode:
    docker:
    - image: circleci/node
    steps:
    - checkout
    - run:
        working_directory: client/vscode
        command: |
          set -e

          npm i

          npm version ${CIRCLE_TAG}
          ./node_modules/.bin/vsce publish -p ${VSCE_TOKEN}
