version: 2.1

release_filter: &release_filter
  filters:
    tags:
      only: /^\d+.\d+.\d+$/
    branch:
      ignore /.*/

workflows:
  build_and_deploy:
    jobs:
    - build_server
    - deploy_server:
        requires:
        - build_server
        <<: *release_filter

server_defaults: &server_defaults
  docker:
  - image: circleci/python

jobs:
  build_server:
    <<: *server_defaults
    steps:
    - checkout
    - run:
        working_directory: server
        command: |
          python3 setup.py sdist bdist_wheel

  check_release:
    <<: *server_defaults
    steps:
    - run: 'true'

  deploy_server:
    <<: *server_defaults
    steps:
    - run:
        working_directory: server
        command: |
          set -e

          [ "${CIRCLE_BRANCH}" != "master" ] && exit

          pip3 install --user twine
          twine upload --repository-url https://test.pypi.org/legacy/ dist/*
