name: Build and Publish to PyPI

on:
  push:
    branches: [master]
    paths:
    - ".github/workflows/publish-pypi.yml"
    - "server/**"
  pull_request:
    branches: [master]
    paths:
    - ".github/workflows/publish-pypi.yml"
    - "server/**"


jobs:
  publish-pypi:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/wdl-lsp
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    defaults:
      run:
        working-directory: server

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Build wheels
      run: python -m pip wheel . --no-deps -w dist

    - name: Publish package distributions to PyPI
      if: github.ref == 'refs/heads/master'
      uses: pypa/gh-action-pypi-publish@release/v1
