name: Build and Publish to VS Code Marketplace

on:
  release:
  pull_request:
    branches: [master]
    paths:
    - ".github/workflows/publish-vscode.yml"
    - "client/vscode/**"

jobs:
  publish-vscode:
    name: Publish release to VS Code Marketplace
    runs-on: ubuntu-latest
    environment:
      name: vscode
    defaults:
      run:
        working-directory: client/vscode

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4

    - name: Build
      run: npm ci

    - name: Publish
      if: github.ref_protected
      run: npm version ${{ github.ref }} &&
           npm run vsce publish -p ${{ secrets.VSCE_TOKEN }}
