name: Build and Publish to JetBrains Marketplace

on:
  release:
    types: [released]
  pull_request:
    branches: [master]
    paths:
    - ".github/workflows/publish-jetbrains.yml"
    - "client/intellij/**"

jobs:
  publish-jetbrains:
    name: Publish release to JetBrains Marketplace
    runs-on: ubuntu-latest
    environment:
      name: jetbrains

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '21'

    - name: Publish Plugin
      if: github.event_name == 'release'
      working-directory: client/intellij
      run: ./gradlew publishPlugin -Ptoken=${{ secrets.JETBRAINS_TOKEN }}
