name: Build and Publish to PyPI

on:
  push:
    branches: [master]
    paths:
    - "server/**"
  pull_request:
    branches: [master]
    paths:
    - "server/**"


jobs:
  publish-pypi:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/wdl-lsp
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
          python-version: "3.10"

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.17

    - name: Publish package distributions to PyPI
      if: github.ref == 'refs/heads/main'
      uses: pypa/gh-action-pypi-publish@release/v1
